name: rsembed
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _python_abi3_support=1.0
  - asttokens=3.0.1
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - comm=0.2.3
  - cpython=3.12.12
  - debugpy=1.8.18
  - decorator=5.2.1
  - executing=2.2.1
  - expat=2.7.3
  - ipykernel=7.1.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.44
  - libedit=3.1.20250104
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libsodium=1.0.20
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - matplotlib-inline=0.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.6.0
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pip=25.3
  - platformdirs=4.5.1
  - prompt-toolkit=3.0.52
  - psutil=7.2.1
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.12.12
  - python-dateutil=2.9.0.post0
  - python-gil=3.12.12
  - python_abi=3.12
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.51.1
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.3
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - aenum==3.1.16
      - affine==2.4.0
      - netCDF4>=1.6
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - alabaster==1.0.0
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.1
      - anywidget==0.9.21
      - attrs==25.4.0
      - babel==2.17.0
      - backcall==0.2.0
      - beautifulsoup4==4.14.3
      - biopython==1.86
      - bleach==6.3.0
      - bqplot==0.12.45
      - branca==0.8.2
      - build==1.4.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cligj==0.7.2
      - cloudpickle==3.1.2
      - contourpy==1.3.3
      - cram==0.7
      - cramjam==2.11.0
      - cuda-bindings==12.9.4
      - cuda-pathfinder==1.2.2
      - cycler==0.12.1
      - dask==2026.1.1
      - defusedxml==0.7.1
      - diffusers==0.36.0
      - docopt==0.6.2
      - docstring-parser==0.17.0
      - docutils==0.22.4
      - donfig==0.8.1.post1
      - earthengine-api==1.7.10
      - eerepr==0.1.2
      - einops==0.8.1
      - fastjsonschema==2.21.2
      - fastparquet==2025.12.0
      - filelock==3.20.0
      - folium==0.20.0
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - ftfy==6.3.1
      - future==1.0.0
      - geemap==0.36.6
      - geocoder==1.38.1
      - geodatasets==2026.1.0
      - geopandas==1.1.2
      - geotessera==0.7.3
      - gitdb==4.0.12
      - gitpython==3.1.46
      - google-api-core==2.29.0
      - google-api-python-client==2.188.0
      - google-auth==2.47.0
      - google-auth-httplib2==0.3.0
      - google-cloud-core==2.5.0
      - google-cloud-storage==3.8.0
      - google-crc32c==1.8.0
      - google-resumable-media==2.8.0
      - googleapis-common-protos==1.72.0
      - grpcio==1.76.0
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httplib2==0.31.1
      - httpx==0.28.1
      - huggingface-hub==1.3.2
      - hydra-core==1.3.2
      - idna==3.11
      - imageio==2.37.2
      - imagesize==1.4.1
      - importlib-metadata==8.7.1
      - importlib-resources==6.5.2
      - ipyevents==2.0.4
      - ipyfilechooser==0.6.0
      - ipyleaflet==0.20.0
      - ipython==8.12.3
      - ipywidgets==8.1.8
      - jinja2==3.1.6
      - joblib==1.5.3
      - jsonargparse==4.45.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter-leaflet==0.20.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - kornia==0.8.2
      - kornia-rs==0.1.10
      - lazy-loader==0.4
      - lightly==1.5.22
      - lightly-utils==0.0.2
      - lightning==2.6.0
      - lightning-utilities==0.15.2
      - locket==1.0.0
      - markdown==3.10.1
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - mistune==3.2.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - narwhals==2.15.0
      - nbclient==0.10.4
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.6.1
      - numcodecs==0.16.5
      - numpy==2.3.5
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.4.5
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - open-clip-torch==3.2.0
      - openai-clip==1.0.1
      - opencv-python-headless==4.13.0.90
      - osmnx==2.0.7
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - partd==1.4.2
      - pickleshare==0.7.5
      - pillow==12.0.0
      - pip-tools==7.5.2
      - pipreqs==0.5.0
      - plotly==6.5.2
      - pooch==1.8.2
      - presto==0.7.7
      - propcache==0.4.1
      - proto-plus==1.27.0
      - protobuf==6.33.4
      - psygnal==0.15.1
      - pyarrow==23.0.0
      - pyasn1==0.6.2
      - pyasn1-modules==0.4.2
      - pycocotools==2.0.11
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyogrio==0.12.1
      - pyparsing==3.3.2
      - pyperclip==1.11.0
      - pyproj==3.7.2
      - pyproject-hooks==1.2.0
      - pyshp==3.0.3
      - python-box==7.3.2
      - pytorch-lightning==2.6.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - rasterio==1.5.0
      - ratelim==0.1.6
      - referencing==0.37.0
      - regex==2026.1.15
      - requests==2.32.5
      - rich==14.2.0
      - rioxarray==0.20.0
      - roman-numerals==4.1.0
      - rpds-py==0.30.0
      - rsa==4.9.1
      - rshf==0.1.12
      - safetensors==0.7.0
      - scikit-image==0.26.0
      - scikit-learn==1.8.0
      - scipy==1.17.0
      - scooby==0.11.0
      - segmentation-models-pytorch==0.5.0
      - sentry-sdk==2.50.0
      - shapely==2.1.2
      - shellingham==1.5.4
      - simsimd==6.5.12
      - smmap==5.0.2
      - snowballstemmer==3.0.1
      - soupsieve==2.8.3
      - sphinx==9.1.0
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - stringzilla==4.6.0
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - terratorch==1.2.1
      - threadpoolctl==3.6.0
      - tifffile==2026.1.14
      - timm==1.0.24
      - tinycss2==1.4.0
      - tokenizers==0.22.2
      - toolz==1.1.0
      - torch==2.10.0
      - torchaudio==2.10.0
      - torchgeo @git+https://github.com/torchgeo/torchgeo.git
      - torchmetrics==1.8.2
      - torchvision==0.25.0
      - tqdm==4.67.1
      - traittypes==0.2.3
      - transformers==5.0.0
      - triton==3.6.0
      - typer==0.21.1
      - typer-slim==0.21.1
      - typeshed-client==2.8.2
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - uritemplate==4.2.0
      - urllib3==2.6.3
      - wandb==0.24.0
      - webencodings==0.5.1
      - werkzeug==3.1.5
      - widgetsnbextension==4.0.15
      - xarray==2025.12.0
      - xyzservices==2025.11.0
      - yarg==0.1.9
      - yarl==1.22.0
      - zarr==3.1.5
      - zipp==3.23.0
      - thor @git+https://github.com/FM4CS/thor_terratorch_ext.git
prefix: /u/dingqi2/miniconda3/envs/torchgeo
